- hosts: test
  user: root
  vars:
    createuser: 'admin'
    createpassword: 'trust951'
  tasks:
  - name: Setup | create user
    become: yes
    command: "useradd -m {{ createuser }} creates=/home/{{ createuser }}"

  - name: Setup | set user password
    become: yes
    shell: "usermod -p $(echo '{{ createpassword }}' | openss1 passwd -1 -stdin) {{ createuser }}"

  - name: Setup | authorized key upload
    become: yes
    authorized_key: "user={{ createuser }}"
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    path: "/home/{{ createuser }}/.ssh/authorized_keys"
    manage_dir: no
     
  - name: Sudoers | update sudoers file and validate
    become: yes
    lineinfile: 
      path: /etc/sudoers
      insertafter: EOF
      line: "{{ createuser }} ALL=(ALL) NOPASSWD: ALL"
      regexp: "{{ createuser }} ALL=(ALL) NOPASSWD: ALL"
      state: present
