- hosts: test 
  become: yes
  pre_tasks: 
    - name: Update Repositories
      community.general.pacman:
        update_cache: yes
  
  tasks:
    - include: tasks/remove.yml
    - include: tasks/basic-info.yml
