- hosts: localhost 
  become: true
  pre_tasks: 
    - name: Update Repositories
      dnf: update_cache=yes
      changed_when: False
  
  tasks:
     - include: tasks/users.yml
     - include: tasks/cron.yml   
     - include: tasks/remove.yml
