- hosts: localhost 
  become: true
  pre_tasks: 
    - name: Update Repositories
      dnf: update_cache=yes
      changed_when: False
  
  tasks:
    - include: tasks/remove.yml
    - include: tasks/gnome.yml
